require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BonspielsController do

  # This should return the minimal set of attributes required to create a valid
  # Bonspiel. As you add validations to Bonspiel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BonspielsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bonspiels as @bonspiels" do
      bonspiel = Bonspiel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bonspiels).should eq([bonspiel])
    end
  end

  describe "GET show" do
    it "assigns the requested bonspiel as @bonspiel" do
      bonspiel = Bonspiel.create! valid_attributes
      get :show, {:id => bonspiel.to_param}, valid_session
      assigns(:bonspiel).should eq(bonspiel)
    end
  end

  describe "GET new" do
    it "assigns a new bonspiel as @bonspiel" do
      get :new, {}, valid_session
      assigns(:bonspiel).should be_a_new(Bonspiel)
    end
  end

  describe "GET edit" do
    it "assigns the requested bonspiel as @bonspiel" do
      bonspiel = Bonspiel.create! valid_attributes
      get :edit, {:id => bonspiel.to_param}, valid_session
      assigns(:bonspiel).should eq(bonspiel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bonspiel" do
        expect {
          post :create, {:bonspiel => valid_attributes}, valid_session
        }.to change(Bonspiel, :count).by(1)
      end

      it "assigns a newly created bonspiel as @bonspiel" do
        post :create, {:bonspiel => valid_attributes}, valid_session
        assigns(:bonspiel).should be_a(Bonspiel)
        assigns(:bonspiel).should be_persisted
      end

      it "redirects to the created bonspiel" do
        post :create, {:bonspiel => valid_attributes}, valid_session
        response.should redirect_to(Bonspiel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bonspiel as @bonspiel" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bonspiel.any_instance.stub(:save).and_return(false)
        post :create, {:bonspiel => { "name" => "invalid value" }}, valid_session
        assigns(:bonspiel).should be_a_new(Bonspiel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bonspiel.any_instance.stub(:save).and_return(false)
        post :create, {:bonspiel => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bonspiel" do
        bonspiel = Bonspiel.create! valid_attributes
        # Assuming there are no other bonspiels in the database, this
        # specifies that the Bonspiel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bonspiel.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => bonspiel.to_param, :bonspiel => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested bonspiel as @bonspiel" do
        bonspiel = Bonspiel.create! valid_attributes
        put :update, {:id => bonspiel.to_param, :bonspiel => valid_attributes}, valid_session
        assigns(:bonspiel).should eq(bonspiel)
      end

      it "redirects to the bonspiel" do
        bonspiel = Bonspiel.create! valid_attributes
        put :update, {:id => bonspiel.to_param, :bonspiel => valid_attributes}, valid_session
        response.should redirect_to(bonspiel)
      end
    end

    describe "with invalid params" do
      it "assigns the bonspiel as @bonspiel" do
        bonspiel = Bonspiel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bonspiel.any_instance.stub(:save).and_return(false)
        put :update, {:id => bonspiel.to_param, :bonspiel => { "name" => "invalid value" }}, valid_session
        assigns(:bonspiel).should eq(bonspiel)
      end

      it "re-renders the 'edit' template" do
        bonspiel = Bonspiel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bonspiel.any_instance.stub(:save).and_return(false)
        put :update, {:id => bonspiel.to_param, :bonspiel => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bonspiel" do
      bonspiel = Bonspiel.create! valid_attributes
      expect {
        delete :destroy, {:id => bonspiel.to_param}, valid_session
      }.to change(Bonspiel, :count).by(-1)
    end

    it "redirects to the bonspiels list" do
      bonspiel = Bonspiel.create! valid_attributes
      delete :destroy, {:id => bonspiel.to_param}, valid_session
      response.should redirect_to(bonspiels_url)
    end
  end

end
